---
taxa_page:
  overview:
    panels:
      - - - panel:gallery
          - panel:type
          - panel:type-specimen
          - panel:nomenclature
          - panel:nomenclature-references
        - - id: panel:biodar-map
            bind:
              cluster: false
              absences: 'off'
          - panel:descendants
          - id: panel:content
            bind:
              en:
                params:
                  topic_id: [2, 3, 4, 6, 8]
              es:
                params:
                  topic_id: [2, 3, 5, 7, 9]
          - panel:keys
          - panel:statistics
          - panel:sounds
